<a href="https://colab.research.google.com/github/Murali-deepln/pytorch_tutoria1/blob/main/pytorch1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch



In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch = my_torch.reshape(2,5)


In [5]:
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch2 = torch.arange(10)


In [7]:
my_torch2 = my_torch2.reshape(2,-1)

In [8]:
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch3 = torch.arange(10)

In [10]:
my_torch4 = my_torch3.view(2,-1)

In [11]:
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
my_torch7[6]

tensor(6)

In [19]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [20]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [21]:
# return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Tensor Math Operations

In [22]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [23]:
# Addition
tensor_a + tensor_b
# adds each item in tensor with respective item in the other tensor

tensor([ 6,  8, 10, 12])

In [24]:
# Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
# substraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [26]:
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [27]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [28]:
# division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [29]:
# division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [30]:
# remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [31]:
# remainder long hand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [32]:
# exponenets
torch.pow(tensor_b,tensor_a)

tensor([   5,   36,  343, 4096])